### ISSUE TITLE
Left swiping from Info to areas works poorly

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#10]
Left swiping shows that there is something to come but it mostly falls back to the page you started on, even though you swipe far left. Example: Open an Info page for an area and try to swipe to areas or crags.

**Comment by bkucsera** [comment]
We worked a lot on swiping but its still not perfect, we have to do a decision in this topic. The problem is that its hard to solve to have several different swiped parts on one screen. In this case, these are: the swipable menu list and and swipeable lower part of screen. 
Now i think we will disable swiping of the menu tabs, so changing between menu tabs (Info/Regions/Areas...) will be available only with clicking on them.
The only swipeable screen will be Topos. What do you think, is it ok for better usability?

**Comment by rouletout** [comment]
I think that's a good plan. i instinctively always tap on the menu item anyways :-)

**Comment by rouletout** [comment]
Works cas expected now, closing
