### ISSUE TITLE
Route count of bigger areas seems arbitrary

### ISSUE THREAD

**Issue by killakalle** [theCrag/tca#121]
**What happened?**

Castellón
Website: 2958
App: 1577

North Portugal
Website: 362
App: 2

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/spain/castellon

Ideally also provide screenshots:

![image](https://user-images.githubusercontent.com/30682796/117071192-0c845780-ad2f-11eb-831d-985dfe365188.png)

![image](https://user-images.githubusercontent.com/30682796/117071518-8288be80-ad2f-11eb-9c55-d47cd1c67870.png)

![image](https://user-images.githubusercontent.com/30682796/117071326-42294080-ad2f-11eb-866a-557fbd53567a.png)

![image](https://user-images.githubusercontent.com/30682796/117071401-5ff6a580-ad2f-11eb-8a09-150907df0275.png)

**What you expected:**

* [ ] Route count (and results) in app matches route count in website

**Comment by rouletout** [comment]
@bkucsera this might merit a look, especially the North Portugal as essentially none of the routes are counted  - I first thought it has to do with located / non-located routes but it doesn't - any ideas?

**Comment by bkucsera** [comment]
This happens only on the Search page, because it shows only the offline available (previously visited) nodes. Once you start a Search, it will show the correct search list. On the node info tab, you see the correct numbers (2958 routes in Castellón or 362 in North Portugal).

If we modify this to show everything on Search tab as well (without Searching, just clicking on the tab), it would mean 5 new requests for the server, to download the metadata.
I think its better to leave it like this to avoid unnecessary server usage, but if this is disturbing, we can modify the code.

**Comment by rouletout** [comment]
Fixed, closing
