### ISSUE TITLE
Swipe back from crag causes that crag to dissappear from the map 

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/tca#64]
If you swipe left one too many times, you end up back at the map - annoying, but fine. 

Only the crag that you were just in isn't there anymore... 

You have to reboot the app due to a misclick, Another option is to click on a different random crag, then go back again, so that the one that has dissappeared is the one that you never cared about

**Comment by bkucsera** [comment]
This happens when there is no selected crag, it happens usually after a new app start.
If there is a selected crag from the map, and you go back from a crag to the map with the back button, you will end up on the map on the selected crag. 

So if you have not chosen any crag on the map, just started browsing the crag list menu and you go back to the map, you would like to see that area/region/country, what you browsed in the list view?

**Comment by DaneEvans** [comment]
No, it's occuring at other times.

In this case, I clicked on an area, went to look through it, accidentally
swiped back, and the dot was no longer there to click on.

Maybe the sensitivity to swipes is too high, because this happened to me at
least 4 times while at the crag on the weekend

**Comment by rouletout** [comment]
@DaneEvans I'm not sure I get it, if I swipe left I'm unable to end up on the map, only on the Index page. Can you check again and maybe supply a screenshot from where this happens? Thx

**Comment by DaneEvans** [comment]
It doesn't seem to be happening at the moment, but I can still go from
index page back to the map.

**Comment by rouletout** [comment]
ok, clsoing this as it seems solved - please re-open if you see that again
