### ISSUE TITLE
Follow the arrow does not do anything

### ISSUE THREAD

**Issue by killakalle** [theCrag/tca#77]
**Reproduce:**

1. Open the topo of any sector
1. Click on Follow the arrow

**Expected:**
Not sure what is supposed to happen here, I guess it should open a map and show me the distance to this crag or start the navigation.

**Actual:**
Nothing happens

![image](https://user-images.githubusercontent.com/30682796/112591669-f9639b00-8e04-11eb-9143-54600449a9f6.png)

**Comment by nicHoch** [comment]
this is not a"button" the arrow should show you (real time updated) the direction and distance to that sector depending on your position. 

@killakalle  please close if your are happy with the answer

**Comment by killakalle** [comment]
@nicHoch 
Not sure I am "happy" with the answer. I understand the functionality now. (maybe hint to you and UX that I did not understand it by myself when I came across it the first time).

I have a couple of follow-up questions:

1. Apparently, this arrow shows only on the "Topos" tab. It does not show on crags that don't have topos, so not able to navigate to crags/boulders that don't have topos. That seems an unnecessary restriction.
2. The arrow takes up a lot of space right under the topo. And it's always there. This assumes that people always use this feature and search for the next crag/boulder. Is that the case? If not, I would put this somewhere else and not take away space from the route list which should be under the topo. Space on mobile is anyhow a lot more precious.
3. "Follow the arrow" for me was not intuitive, i.e. I thought it would start a navigation app. Also, as you can see in the screenshot, I'm 978km away from that place. I won't start following the arrow. =) Maybe it should be "Direction and distance to crag/boulder/..." or something similar. Probably worth to hear feedback from other people who don't know this feature, yet.

PS:
What's the meaning of this? That confused me also, and I tried clicking it. Maybe just remove it.
![image](https://user-images.githubusercontent.com/30682796/112703806-886dc300-8e98-11eb-809e-fdff6ac3e9bd.png)

**Comment by DaneEvans** [comment]
In terms of the usability; I figured out what it was, but I have never used
it.

I'm either already standing under the wall, in which case it's useless (and
often telling me to go 50m in some arbitrary direction),

or I'm a long way away, and need road directions not an arrow.

It's another 'feature' that might work well on a heavily sanitised and
curated data set, with multiple averaged geotags per climb, and for every
climb,

but for the state of a user generated one, where areas are roughly located,
and boulders/crags and routes aren't, it will struggle to be an effective
tool. It may help to increase the quality of the data provided, but I
expect that it will increase frustration and complaints, rather than
encourage contribution

**Comment by killakalle** [comment]
>I'm either already standing under the wall, in which case it's useless (and
often telling me to go 50m in some arbitrary direction), or I'm a long way away, and need road directions not an arrow.

I agree with the above

A valuable use case for the feature that I can imagine at the moment - but I haven't tried it - is if you are in the middle of a boulder field and would like to locate one particular boulder.

**Comment by rouletout** [comment]
Maybe we should consider disabling this for theCrag content?

**Comment by rouletout** [comment]
Put the arrow if less than 2km, if more put navigation

**Comment by rouletout** [comment]
works fine - closing
