### ISSUE TITLE
Turning the device leads to "white screen"

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#8]
Opening a list of areas (with web-covers, eg sub-areas of Zillertal) in landscape on my tablet and then turning the tablet by 90° to portrait mode only shows an empty page with the black header.

After a while a pop-up shows up that says: Package Installer has stopped, Close App

**Comment by bkucsera** [comment]
Normally the landscape mode is not allowed in the app in general. We just forgot to disable it in the beta version. We fix it with the next release, so the app will work only in portrait mode (as the existing TG app does).

**Comment by lordyavin** [comment]
Why should landscape mode be disabled?

**Comment by bkucsera** [comment]
We disable it, because the the design plan requires it, as most of the screens have list views. If we were enable it, it would make the UX work much harder and it does not have a big positive impact on user experience. In usability its better to have a fix view in many apps (facebook, instagram, spotify, etc...)

**Comment by rouletout** [comment]
Doesn't turn anymore, closed
